### ISSUE TITLE
Examples for file loading please !

### ISSUE THREAD

**Issue by touchft** [GenieFramework/StippleUI.jl#12]
The UI is simply shown ahead of the code.

![11](https://user-images.githubusercontent.com/12428354/105867234-d2206580-602f-11eb-8855-10b0e05310b1.png)

I try to hybrid various examples and get the following code. Unfortunately it is NOT working! Please provide an example for file loading. Thank you!! 

```julia
using Stipple
using StippleUI
using Genie, Genie.Requests
using StippleUI:form

Base.@kwdef mutable struct RDModel <: ReactiveModel
    files::R{Dict{String,Any}} = Dict{String,Any}()
    fileloaded::R{Any} = nothing
end

const model = Stipple.init(RDModel(), debounce = 0)

function ui(model::RDModel)
[
    dashboard(root(model), class="container", title="Tools", [
        card( bordered=true, [
            card_section(class="text-subtitle1",[
                "6. Select Folder/Path to Save Data"
            ])
            separator()
            form([                
                    filefield("Choose path/folder to save files", :files, name="fileloaded", bottomslots=true, 
filled=true, counter=true, clearable=true )
                    btn(label="Submit", type="submit", color="primary", icon="cloud_upload")
                ], action="/upload",method="post", enctype="multipart/form-data","@submit='onSubmit'")
        ])
    ])
]
end

route("/") do
    ui(model) |> html
end

route("/upload", method = POST) do
    if infilespayload(:files)
      display(filespayload(:files))
      write(filespayload(:files))
      display(filename(filespayload(:files)))
      stat(filename(filespayload(:files)))
    else
      "No file uploaded"
    end
end

up()
```

**Comment by touchft** [comment]
Comparing with quasar and Genie introduction and binding-relation with vue, I made a guess to bind the file name and julia, and finally it WORKs !

Simply replace `name="fileloaded"` by `name=files` ! The above code WORKs!

I hope more examples and I don't want to kill my brain again. ^_^

**Comment by touchft** [comment]
One thing I am confused for the symbol `:files` in above code:

```julia
route("/upload", method = POST) do
    if infilespayload(:files)
      display(filespayload(:files))
      write(filespayload(:files))
      display(filename(filespayload(:files)))
      stat(filename(filespayload(:files)))
    else
      "No file uploaded"
    end
end
```

How is `:files` related with `model.files` ? If we have `a.files`, `b.files`, etc, how do we control which `:files` to be referenced for uploading?

**Comment by essenciary** [comment]
@touchft I see your point - the above code is not designed to work with Stipple (eg is not reactive). Let me take a look, we need to find an optimal workflow.

**Comment by hhaensel** [comment]
BTW, there is a quasar uploader component. You can easily integrate it yourself by calling
```
Genie.Renderer.Html.register_normal_element("q__uploader", context = @__MODULE__)
uploader(args...; kwargs...) = q__uploader(args...; attributes([kwargs...], StippleUI.API.ATTRIBUTES_MAPPINGS)...)
```
and then use the component by
```
uploader(label = "Upload my very important file", url = "/upload", style = "max-width: 500px", accept = ".jpg")
```

**Comment by hhaensel** [comment]
@essenciary We should integrate the uploader in StippleUI? Shall I do it?

(I have not completely understood, why you put a template wrapper by default for most of your components. Could you explain this to me or could you give an example where this is useful?
And should I enclude a wrapper for the upload component?)

**Comment by essenciary** [comment]
That'd be awesome, thank you! 

Quasar components are to be wrapped in `<template>` because template HTML code is not rendered by the browser when the page is loaded. The template (or rather it's content) is not meant to be rendered before the JS kicks in as it's just DOM content for building the web components after the JS is loaded. Ex: https://quasar.dev/vue-components/file-picker#Design - check out the source for the examples and you'll see they're always wrapped in `<template>`. 

The issue is that `Gumbo` has a bug which wipes away the `<template>` tags. I've opened a ticket months ago but I don't think it was resolved yet. So for Genie view code that goes through Gumbo, the `<template>` tags needs to be substituted for something else.

**Comment by hhaensel** [comment]
Done, see #11 

you can use now `uploader()` with the latest master. Furthermore there are `quasar()`, `quasar_pure()`, `vue()` and `vue_pure()` to use non-registered quasar and vue components with and without template wrapping, e.g.
```
julia> uploader(label = "Upload my very important file", url = "/upload", style = "max-width: 500px", accept = ".jpg")
"<template><q-uploader label=\"Upload my very important file\" url=\"/upload\" style=\"max-width: 500px\" accept=\".jpg\"></q-uploader></template>"

julia> quasar(:uploader, label = "Upload my very important file", url = "/upload", style = "max-width: 500px", accept = ".jpg")
"<template><q-uploader accept=\".jpg\" url=\"/upload\" label=\"Upload my very important file\" style=\"max-width: 500px\"></q-uploader></template>"

julia> list(item(:test))
"<template><q-list><q-item>test</q-item></q-list></template>"

julia> quasar(:list, quasar_pure(:item, :test))
"<template><q-list><q-item>test</q-item></q-list></template>"

julia> vue(:slider,"", @bind(:a), tooltip=@data("'always'"), "order=false, :dot_size=15")
"<template><vue-slider :tooltip=\"'always'\" v-model='a' order=false, :dot_size=15></vue-slider></template>"
```
Note:
- the first regular argument appears as element between the opening and closing brackets. This is the reason for the `""` after `:slider`
- further regular arguments are supplied as attributes, so you can use raw js text. This is currently still necessary for numbers, booleans, and arrays until https://github.com/GenieFramework/Genie.jl/pull/337 is merged.

**Comment by hhaensel** [comment]
@touchft Can we close this?

**Comment by touchft** [comment]
Sorry, I am late. ^_^
