### ISSUE TITLE
notify doesn't work with Dict

### ISSUE THREAD

**Issue by yakir12** [GenieFramework/StippleUI.jl#123]
I'm trying to notify the client about some error. The error message I compose may contain a string representation of a `Dict`. It would seem that if the message contains the `Pair` operator, `=>`, then it doesn't display on the client's side.
MWE:
```julia
msg = "this works"
notify(model, msg, html=true)

msg = string(Dict(() => ()))
notify(model, msg, html=true) # this doesn't work
```

**Comment by yakir12** [comment]
Oops (fixed), regardless, perhaps this illustrates the problem more clearly:
```julia
msg = "this works"
notify(model, msg, html=true)

msg = "this doesn't =>"
notify(model, msg, html=true) # this doesn't work
```

**Comment by hhaensel** [comment]
@yakir12 I found the culprit. I had it on my list already quite some time ago, but had not realised that it was also the root cuase for this issue. So feel free to use "=>" from now on in your strings ...

**Comment by yakir12** [comment]
Awesome thanks!
