### ISSUE TITLE
Missing import of @kwdef for early Julia versions

### ISSUE THREAD

**Issue by yakir12** [GenieFramework/StippleUI.jl#124]
I'm really just trying to help push along some of the work Adrian did in https://github.com/GenieFramework/StippleUI.jl/commit/c2f47b383e86cfd628f699c765d78d40a7c6f9f2
I think you need to add 
```julia
Base.VERSION < v"1.8" && import Base.@kwdef
```
in `__init__()` somewhere...?

**Comment by essenciary** [comment]
@yakir12 ah ouch, thanks for pointing this. Maybe easier to just replace `@kwdef` with `Base.@kwdef`.

**Comment by essenciary** [comment]
Done, tagged a new release ;-)

**Comment by essenciary** [comment]
Absolutely no worries, it was a quick fix and I appreciate the heads-up. Had it been a longer fix, I would've asked you if you can submit a PR :)
