### ISSUE TITLE
Button not working if initialized as true

### ISSUE THREAD

**Issue by svilupp** [GenieFramework/StippleUI.jl#129]
Behaviour: When a variable associated with a button is initiated as true, it will never become reactive. See MWE below

MWE
```julia
using GenieFramework
@genietools

@app begin
    @in process = true # change this to false and all will work as expected

    @onbutton process begin
        @info "Button clicked"
    end
end

function ui()
    btn("Send", @click(:process))
end

@page("/", ui)
Genie.isrunning(:webserver) || up()
```

Versions:
- Julia 1.10.0
- GenieFramework v1.26.11 // tried v2.0.0 and same problem

**Comment by hhaensel** [comment]
That's the expected behaviour. If you want that the button is pressed right at the beginning, you should trigger it upon isready:
```julia
@app begin
    @in process = true # change this to false and all will work as expected

    @onbutton process begin
        @info "Button clicked"
    end

    @onchange isready begin
        process = true
    end
end
```

**Comment by svilupp** [comment]
Good to know, took me 2 hours of debugging! Thank you.

**Comment by hhaensel** [comment]
Sorry to hear that. Happy coding anyway.
We're currently bringing Genie to Vue3/Quasar2 so stay tuned.

**Comment by svilupp** [comment]
Exciting!

@hhaensel, would you mint commenting on why does initialization value break everything? 

It doesn't fit with my mental model of how Stipple works.
When debugging, I saw that the HTML look correct (v- attributes), the VUE inspector looked correct, the generated model in .js looked correct, etc.

1) why does =true break its functionality?
2) where would YOU look to debug such issue?

Thank you!

**Comment by svilupp** [comment]
There is definitely something else going on - in past versions of StippleUI, I could use:
`@click("btn_reset=!btn_reset")` inside a button, but that no longer works either. It must be `@click(:btn_reset)`

**Comment by essenciary** [comment]
@svilupp not sure what you'd expect to happen in your initial example. What happens is that you set `process` to `true` and the button's click also sets it to `true`. So when you click it, nothing happens. 

---

> where would YOU look to debug such issue?

Here I just looked in the browser's inspector: 
a) no errors
b) `process` is already `true`
<img width="204" alt="image" src="https://github.com/GenieFramework/StippleUI.jl/assets/11292378/72affe40-498b-47ab-87a2-453a86b6630c">
c) page source shows that onclick event does not change the value: 
<img width="389" alt="image" src="https://github.com/GenieFramework/StippleUI.jl/assets/11292378/94bb7291-5492-4729-9678-3def419c8efd">

**Comment by essenciary** [comment]
> There is definitely something else going on - in past versions of StippleUI, I could use: `@click("btn_reset=!btn_reset")` inside a button, but that no longer works either. It must be `@click(:btn_reset)`

You can still use that. Per my tests snippets: 

```
@onbutton process begin
    @info "Button clicked"
end

@onchange process begin
       @info "Changed"
end

function ui()
       btn("Send", @click("process = !process"))
end
```

However I see something wrong @hhaensel 

a) initially `process` is `true`
b) upon click, only the `changed` handler is triggered, not the `onbutton` -> `process` switches to `false`
c) after that, `changed` gets triggered twice (presumably changing `process` twice which stays `false`, never becoming `true`)

REPL output: 
<img width="356" alt="image" src="https://github.com/GenieFramework/StippleUI.jl/assets/11292378/fea76291-6a57-4fbd-aee7-ace7a6ed19a3">

Console output:
<img width="208" alt="image" src="https://github.com/GenieFramework/StippleUI.jl/assets/11292378/8793e017-2595-4cee-99f5-1d5c513a832e">

**Comment by hhaensel** [comment]
That's all normal, I'd say.
`@onbutton` looks for a switch from false to true, executes the handler and sets the button back to false. If you'd print `"changed to $process"` you would see that.

**Comment by hhaensel** [comment]
If you want a different behaviour, use the `@onchange process` and do the handling yourself.

**Comment by hhaensel** [comment]
When you set `loading = :process` the button starts spinning and waits for being set true. I think in that case you cannot change the buttons's state by clicking.

**Comment by svilupp** [comment]
Closing as answered! Thank you
