### ISSUE TITLE
Uploader is missing fieldname to connect it to the model

### ISSUE THREAD

**Issue by yakir12** [GenieFramework/StippleUI.jl#15]
If I understood this right, [uploader](https://github.com/GenieFramework/StippleUI.jl/blob/773f1420e69ac255270bd6ba9d0037400eeb43b5/src/Uploader.jl#L10) doesn't have the `fieldname` attribute so it's impossible (for me) to link it to a parameter in the model (like what exactly gets updated once someone uploads a file). Also, I'm not sure what exactly the uploader is supposed to return, a temp file path to the uploaded file, or perhaps something else.

Gonna politely ping my own guide in this journey... @hhaensel 

I might be totally off...

I just found Genie's documentation about [file uploads](https://genieframework.github.io/Genie.jl/dev/tutorials/8--Handling_File_Uploads.html), so now I'm a bit confused.

**Comment by hhaensel** [comment]
It's a two-step process:

1) put the uploader in your `ui()`
```
quasar(:uploader, label = "Upload new files", url = "/upload", accept = ".txt") )
```
2) add a route that handles the request
```
route("/upload", method = POST) do
    # route for uploading a file
    # see also documentation of Genie / API / Requests
    files = Genie.Requests.filespayload() # type: Dict{String, Genie.Input.HttpFile}
    for f in files
        @info "Uploading: " * f[2].name
        write(joinpath(targetdir, f[2].name), String(f[2].data))
    end
end
```

I hope that I didn't make any errors during adaptation here.

**Comment by yakir12** [comment]
Once Stipple's documents are up, this should go there. I'll leave this open as a reminder for the docs, or feel free to close this -- it did completely solve my problem of uploading. Thanks!!!

**Comment by hhaensel** [comment]
Can we close this?
I want to mention that `uploader()` is already part of StippleUI, so you can call it directly.
```
uploader(label = "Upload new files", url = "/upload", accept = ".txt")
```

**Comment by yakir12** [comment]
Sounds good to me!
