### ISSUE TITLE
Reload page at the end of @click

### ISSUE THREAD

**Issue by jbrea** [GenieFramework/StippleUI.jl#17]
Is there a simple way to tell the page to reload in Stipple?
I have a button `btn("plot", @click("plot = true")` and
```julia
on(model.plot) do _
    if (model.plot[])
        render()
        # trigger something like window.location.reload(true) in javascript: how do I do that?
        model.plot[] = false
    end
end
```
Currently I reload the page manually after having pressed the plot button, but it would be nice if the button click automatically reloaded the page.

**Comment by hhaensel** [comment]
What's the reason for reload? Normally, you should update your plot via the webchannel without a full reload.
If you still need a reload, you can call `location.reload()`. Possibly via a local method defined by `js_methods()`.
How to do that you can read [here](https://discourse.julialang.org/t/call-a-vue-function-in-a-stipple-app/56466/6) and [here](https://discourse.julialang.org/t/how-to-use-btn-toggle-in-stipple/56501).

**Comment by jbrea** [comment]
> What's the reason for reload?

I have a `plot_data::R{Vector{PlotData}}` field in my model to plot curves with `StipplePlotly`.
The `render()` function empties the `plot_data` field and pushes some new `PlotData` onto that list.
I couldn't figure out a way to display the new list of `PlotData` without reloading the page.

Thanks for the help!

(I realised it may have been better to ask on discourse or gitter. Shall I close this issue and move the conversation there?)

**Comment by hhaensel** [comment]
Have a look at the [MultiUser](https://github.com/GenieFramework/StippleDemos/blob/master/MultiUserApp.jl) example in the StippeDemos.

**Comment by jbrea** [comment]
I tried to do the same as in the link you posted, but I may be missing something important: it doesn't seem to work.
Here is a M(N)WE (it works in the sense that it works when I manually reload the page).

```julia
using Stipple, StippleUI, StipplePlotly, Genie

Base.@kwdef mutable struct Model <: ReactiveModel
    plot::R{Bool} = false
    layout::R{PlotLayout} = PlotLayout()
    plot_data::R{Vector{PlotData}} = []
end

const model = Stipple.init(Model())

function ui()
    on(model.plot) do _
        if (model.plot[])
            empty!(model.plot_data[])
            push!(model.plot_data[], PlotData(x = 1:10, y = rand(10)))
            model.plot[] = false
        end
    end

    page(vm(model), class = "container", [
            plot(:plot_data, layout = :layout),
            btn("plot", @click("plot = true"))
         ]) |> html
end

route("/", ui)
up()
```

This is with
```
Genie v1.16.0
Stipple v0.9.2
StippleUI v0.2.4
StipplePlotly v0.1.0
```

**Comment by hhaensel** [comment]
There are two problems with your code:
- you create a new listener with each execution of your `ui()` definition. This is not a problem if you run the file once, but if you are debugging, you end up with many listener functions which all execute and produce their respective errors.
- you changed the content of an array by `empty!` and `push!` This doesn't trigger the listener functions unfortunately!). One way out is to call notify!(model.plotdata). That is reasonable, if you add another plotseries. If you want to only create a new single series you can assign a new Array of plot_data to `model.plot_data[]`.
My code would look like
```
using Stipple, StippleUI, StipplePlotly, Genie

Base.@kwdef mutable struct Model <: ReactiveModel
    plot::R{Bool} = false
    layout::R{PlotLayout} = PlotLayout()
    plot_data::R{Vector{PlotData}} = []
end

function restart()
    model = Stipple.init(Model())
    on(model.plot) do plot
        plot || return
        if length(model.plot_data[]) >= 5
            model.plot_data[] = [PlotData(x = 1:10, y = rand(10))]
        else
            push!(model.plot_data[], PlotData(x = 1:10, y = rand(10)))
            notify!(model.plot_data)
        end
        model.plot[] = false
    end
end
restart()

function ui()
    page(vm(model), class = "container", [
            plot(:plot_data, layout = :layout),
            btn("plot", @click("plot = true"))
         ]) |> html
end

route("/", ui)
up()

```

**Comment by hhaensel** [comment]
I must admit, that I did this definition of `on()` in the `ui()` function in my demo code. That is not good practice. I will change this. - I also learn with time 😉

**Comment by jbrea** [comment]
Awesome, thanks a lot. The version with assignment of a new array to `model.plot_data[]` works perfectly.

I couldn't find the function `notify!`, But I don't need this version, because I'm happy with the assignment of a new array.

**Comment by hhaensel** [comment]
I've written the example in that way that the `on()` routine checks how many traces are displayed (`length(model_plotdata[])` >=5). In that case I assign a new array.
If there are less than 5 traces I add a new trace with `push!()` similar what you did in your example, but without emptying the array beforehand. Then I call `notify!()` which is automatically imported from Observables by Stipple.

**Comment by jbrea** [comment]
Ah, great, now also the `notify!` version works. For my version of Stipple I had to call explicitly `Stipple.Observables.notify!`.
