### ISSUE TITLE
Not all Quassar Vue Components included in StippleUI

### ISSUE THREAD

**Issue by szafna** [GenieFramework/StippleUI.jl#2]
Hi,

as I've found out from source not all Quassar Vue Components are includede in stippleUI pkg.
Components like FilePicker, Tab/Tab panels, Toolbar are just few of not included.

 Is there a plan to extend the pkg? It would be nice if the whole Quasar Component library will be included.
Is there an option to include missing components myself?

Si

**Comment by essenciary** [comment]
@szafna Yes, I will keep adding more components, with a focus on most commonly used ones. So I'm not sure we'll ever have all of them, 100% coverage of the Quasar API is not a goal. But the ones you mention we'll most likely have. 

I you want to contribute, that'd be much appreciated - it's about adding Julia wrappers for the missing components, similar to the ones already available.

**Comment by szafna** [comment]
@essenciary I do not have competences yet for building wrappers (Julia and html/js beginner). Will try after while I get some more skills.

**Comment by essenciary** [comment]
Thank you - I will set up some docs on how to develop components, hopefully that will help.

**Comment by hhaensel** [comment]
I have a proposal to make in order to make adding features easier. As an example I have taken [`textfield()`](https://github.com/GenieFramework/StippleUI.jl/blob/master/src/FormInput.jl#L15-L152) from `FormInput` and modified it so that it does the same job, but is easier to maintain and adapt for other features.

The key idea is to replace '-' characters by '_' and to loop over the parameters. That way we would keep the nice feature that typical paramters are listed in the documentation or when pressing tab in the REPL, but the text is much shorter. There is practically no performance reduction (66µs vs. 65µs)
```
function textfield(
                    fieldname::Union{Symbol,Nothing} = nothing,
                    args...;
                    label::String = "",
                    label_color::Union{String,Nothing} = nothing,
                    label_slot::Union{String,Nothing} = nothing,
                    bg_color::Union{String,Nothing} = nothing,
                    input_class::Union{String,Nothing} = nothing,
                    input_style::Union{String,Nothing} = nothing,
                    clear_icon::Union{String,Nothing} = nothing,
                    fill_mask::Union{String,Nothing} = nothing,
                    rules::Union{String,Nothing} = nothing,
                    error_message::Union{String,Nothing} = nothing,
                    shadow_text::Union{String,Nothing} = nothing,
                    bottom_slots::Bool = false,
                    stack_label::Bool = false,
                    unmasked_value::Bool = false,
                    reverse_fill_mask::Bool = false,
                    lazy_rules::Bool = false,
                    reactive_rules::Bool = false,
                    no_error_icon::Bool = false,
                    hide_hint::Bool = false,
                    hide_bottom_space::Bool = false,
                    item_aligned::Bool = false,
                    kwargs...)

    kk = (
        :label_color, :label_slot, :bg_color, :input_class, :input_style, :clear_icon, :fill_mask, :rules, :error_message,
        :shadow_text, :bottom_slots, :stack_label, :unmasked_value, :reverse_fill_mask, :lazy_rules, :reactive_rules, 
        :no_error_icon, :hide_hint, :hide_bottom_space, :item_aligned
        )
    vv = (
        label_color, label_slot, bg_color, input_class, input_style, clear_icon, fill_mask, rules, error_message,
        shadow_text, bottom_slots, stack_label, unmasked_value, reverse_fill_mask, lazy_rules, reactive_rules, 
        no_error_icon, hide_hint, hide_bottom_space, item_aligned
        )
      
    k = (:label, )
    v = Any[label]

    if fieldname !== nothing
        k = (k..., Symbol("v-model"))
        push!(v, fieldname)
    end

    for (k_new, v_new) in zip(kk, vv)
        if !(isnothing(v_new) || (typeof(v_new)==Bool && !v_new))
            k = (k..., Symbol(replace(String(k_new), "_" => "-")))
            push!(v, v_new)
        end
    end
    
    template() do
        q__input(; kwargs..., NamedTuple{k}(v)...)
    end
end
```

**Comment by essenciary** [comment]
@hhaensel the `FormInput` implementation is "deprecated". That integration was the first iteration, I have since abstracted away the integration into a different API which is much cleaner. We have come pretty much to similar approaches, see https://github.com/GenieFramework/StippleUI.jl/blob/master/src/Badge.jl

I'm in progress of updating the "legacy" components to this new API.

**Comment by essenciary** [comment]
Thank you everybody for the input! 

I'm doing a bit of cleanup and I'll close this as the API seems to have stabilized and I've planned a list of core UI components for v1: 
https://github.com/GenieFramework/StippleUI.jl/projects/1

**Comment by hhaensel** [comment]
I've just added raw components, which make it possible to use non-registered components.
See #11 and #12
