### ISSUE TITLE
extend

### ISSUE THREAD

**Issue by cwiese** [GenieFramework/StippleUI.jl#32]
Love Stipple's design over Dash.   Is there a document on adding Quasar components like "autocomplete"??

**Comment by cwiese** [comment]
also this should work right?

`Stipple.select(:yfeature; options=:features, **multiple=true**)`

**Comment by hhaensel** [comment]
Yes, indeed that works, you can even do
`multiple=:multiplefeatures` and change whether the option field accepts multiple selections by setting `model.multiplefeatures[] = true`.
But you need to write your own logic in the backend what to do with the value of features.
Also, you have to define yfeatures as a Vector. Luckily, the backend always converts atomic values to 1-element Vectors if the field is a Vector :-)

**Comment by hhaensel** [comment]
According to the quasar docs you need to insert `  <q-autocomplete
    @search="search"
    :min-characters="3"
    @selected="selected"
  />` in the input field. You can either do that manually as a string or use the `quasar()` function, e.g.
```julia
quasar_pure(:autocomplete, "",
    @on(:search, "search"),
    min__characters=R"3",
    @on(:selected, "selected"))
 ```
As I am currently on my mobile phone this code is not tested. Concerning registration of QAutocomplete, @essenciary is the specialist.
Good luck. We should include this in a demo if it works!

**Comment by cwiese** [comment]
I see what you mean ..I get 
```vue.js:634 [Vue warn]: Unknown custom element: <q-autocomplete> - did you register the component correctly? For recursive components, make sure to provide the "name" option.```

I have tried Genie.Renderer.Html.register_normal_element("q__autocomplete", context = @__MODULE__)

**Comment by hhaensel** [comment]
It's nevertheless q-select. We chose the API to omit the `q-` for all elements. So you find item for q-item, toggle for q-toggle, etc.
You can always check the content by entering the expression at the REPL.

**Comment by hhaensel** [comment]
I guess it's the same problem as with qtab. Try to use the normal elements with a closing </q-route-tab>. This automatically happens if you define your own function similar to my example above

**Comment by cwiese** [comment]
this does not solve it .. I am converting to quasar_pure functions to test 

```
          <q-tabs align="left">
            <q-route-tab to="/page1" label="Page One" ></q-route-tab>
            <q-route-tab to="/page2" label="Page Two" ></q-route-tab>
            <q-route-tab to="/page3" label="Page Three" ></q-route-tab>
          </q-tabs>
```

**Comment by hhaensel** [comment]
@cwiese 
For the future, please open new issues for new topics, because it's difficult to find anything after a while 😉

**Comment by hhaensel** [comment]
Coming back to the router tab:
I think router works differently than you expect. For that to work you have to link the vue router js ànd initialise a router component. For more information have a look at https://router.vuejs.org/guide/#javascript
I propose you open a new issue with a description what you are going to achieve.

**Comment by hhaensel** [comment]
@cwiese I close this issue as it is becoming very long.
Please feel free to open a new issue if you think you need router support. As we havie the Genie router in the backend, I think having another router component is rather confusing.

**Comment by cwiese** [comment]
Yes confusing but .. we used Ember.js for a long time and like Single Page Apps (SPA) that have routers that can manage "parts" of the page without visiting the server (except for maybe a REST call for data).  The part we like is a route like /customer/10/item/20 can render a parmet form (customer 10) and and item they purchased expanded Master Detail for example.  THis would be hard with Server generated code (although Ember does it also)

**Comment by essenciary** [comment]
I'd say that the best way to achieve this would be to tap into the Vue ecosystem (https://router.vuejs.org) as in theory it should provide the best implementation. We could add some friendly API to include/interact with Vue router. As @hhaensel said, can you please open a new issue where you provide a MWE?
