### ISSUE TITLE
Model property as a dictionary 

### ISSUE THREAD

**Issue by cwiese** [GenieFramework/StippleUI.jl#37]
is it possible to bind to a Key of a dictionary in in the model?   `  params::R{Dict} = Dict()`

how would i create the expression ?  @bind(:params["key"]) ==> obviously that will not work 

 ```
 q__input("", @bind(:params, :key), outlined=true, label="direction", stack__label=true, dense="dense")

 Stipple.@kwdef mutable struct HomeModel <: ReactiveModel
  data::R{DataTable} = DataTable()
  params::R{Dict} = Dict()
end #home

params = Dict("key"=>"value1", "key2" = "value2")
  ```

**Comment by cwiese** [comment]
I tried "computed" ... I really trying to avoid creating 25 top level attributed ..it could be dynamic 
```
Stipple.js_computed(dash_model::MainDash) = """
  key: function () {
    return this.params["key"]
  }
"""
```

**Comment by hhaensel** [comment]
You can use Dicts without computing the value:
```julia
toggle("Label", Symbol("""params["key"]"""))
```
or
```julia
@bind("""params["key"]""")
```
if you need it explicitly in another element.

**Comment by hhaensel** [comment]
For input fields we have `numberfield` and `textfield` that bind numeric values or string values, e.g.
```julia
textfield("direction", R"""params["key"]""", :outlined, :stack__label, dense = "dense")
```

```julia
julia> textfield("direction", R"""params["key"]""", :outlined, :stack__label, dense = "dense") |> println
<template>
<q-input label="direction" v-model="params["key"]" dense="dense" outlined stack-label>

</q-input>

</template>
```

**Comment by hhaensel** [comment]
In the example above I used the fact that the R_str macro generates symbols from strings. Not sure, whether @essenciary likes this usage 😉 
A number field would look like this
```julia
julia> numberfield("direction", R"""params["key"]""", :outlined, :stack__label, dense = "dense") |> println
<template>
<q-input label="direction" v-model.number="params["key"]" dense="dense" outlined stack-label>

</q-input>

</template>
```
If you want to bind a typed field in a pure element, you would use
```julia
julia> @bind("""params["key"]""", :number)
"v-model.number='params[\"key\"]'"
```

**Comment by cwiese** [comment]
this is great information, thank you.  will test very soon

**Comment by hhaensel** [comment]
@cwiese Did you test?
@essenciary shall we change or enhance the `@bind` syntax, as I proposed [here](https://github.com/GenieFramework/Stipple.jl/issues/67#issuecomment-962988342), I think that got lost

**Comment by cwiese** [comment]
Yes it worked perfectly I appreciate the insight
