### ISSUE TITLE
How to nest elements 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [GenieFramework/StippleUI.jl#41]
Quasar component 

```
<q-btn
        type="submit"
        :loading="submitting"
        label="Save"
        class="q-mt-md"
        color="teal"
      >
        <template v-slot:loading>
          <q-spinner-facebook />
        </template>
</q-btn>
```

What will be the stipple alternative?

both `q__btn` and `q__spinner` are defined I believe

**Comment by hhaensel** [comment]
What about this one:
```julia
btn("save", type = "submit", loading = :submitting, 
    class="q-mt-md", color="teal", [

    template("", "v-slot:loading", [
        spinner(:facebook, wrap=StippleUI.NO_WRAPPER)
    ])
])
```
The empty string after template is necessary to have the `v-slot` appearing in the parameters. The content in square brackets is always placed as inner element. I use this for both, `btn()` and `template()`.

**Comment by AbhimanyuAryan** [comment]
Thankyou will try it 😁

**Comment by AbhimanyuAryan** [comment]
@hhaensel comes up with this script as well does work without this. How do I use this JS and put in Stipple?  Also simulating a delay. I'm running a backend db search with Genie and want it to keep loading till backend operation is done. 

      // Simulating a delay here.
      // When we are done, we reset "submitting"
      // Boolean to false to restore the
      // initial state.

```
<script>
import { ref } from 'vue'

export default {
  setup () {
    const test = ref('')
    const submitting = ref(false)

    function simulateSubmit () {
      submitting.value = true

      // Simulating a delay here.
      // When we are done, we reset "submitting"
      // Boolean to false to restore the
      // initial state.
      setTimeout(() => {
        // delay simulated, we are done,
        // now restoring submit to its initial state
        submitting.value = false
      }, 3000)
    }

    return {
      test,
      submitting,
      simulateSubmit
    }
  }
}
</script>
```

**Comment by AbhimanyuAryan** [comment]
Also this example has `spinner` component as nested element of `imageview`. Quasar complement of this is: ```<q-img> <q-spinner></q-spinner> </q-img>``` <--- something like that


https://github.com/GenieFramework/StippleDemos/blob/1fbd312947199f30f9931963b999cec02590e6f5/BasicExamples/ImageGallery.jl#L42


Looking forward to you first PR in *StippleUI*. Let me know if anything not clear :D
