### ISSUE TITLE
Using observables with quasar table object

### ISSUE THREAD

**Issue by szafna** [GenieFramework/StippleUI.jl#8]
Hi,

I'd like to use selection functionality of table object:
  variable selection::R{Vector{String}} is defined in ReactiveModel
also
  DataTableOptions(true, "ID",nothing)
is defined in DataTable variable simulation
```Julia
table(:simulation; selection = "single")
```
shows table with selection checkboxes. Next is to add observables variable :selection  that should get ID of selected row.
I've not found a way how to do this. 
Could someone give same help.

Si

**Comment by essenciary** [comment]
@szafna Yes, I remember that I noticed this wasn't working properly. I'll take a look and follow up.

**Comment by szafna** [comment]
@essenciary I've found out that data type returned from client (quasar) is not String. It is Dict. Hence variable definition of ``` selection``` should be ```  selection::R{Vector{Any}} = []```. It is same for single and multiple selection option in q_table property .
Si
