### ISSUE TITLE
rtl support

### ISSUE THREAD

**Issue by j209** [GenieFramework/StippleUI.jl#81]
Quassar framework support right-to-left(RTL) for rtl cultures like arabic,hebr,persian...
Can we expect Stipple to support right to left as well?

**Comment by AbhimanyuAryan** [comment]
closing in favor of discussion. Not really an issue 🙂

**Comment by essenciary** [comment]
@j209 I'm not familiar with this. What's needed to make it work? What have you tried and didn't work?
