### ISSUE TITLE
Updating part of HTML code using observables

### ISSUE THREAD

**Issue by szafna** [GenieFramework/StippleUI.jl#9]
Hi,

i have a String with HTML code in a \<div>. It is result of some calculation in Julia. What I would like to achieve is that after calculation (click on button) a \<div> with HTML code is replaced with new content. Therefore there should be a kind of link (observables) between my String that contains HTML code and \<div> object in Stipple app.
Instead of \<div>, other containers can also be used  like \<iframe>. With \<iframe> I would like dynamically change link in src= url link

How can I approach to this? Any help will be appreciate.

si

**Comment by essenciary** [comment]
@szafna Check out these examples showing how to bind click events to Julia functions and update the UI: 
https://github.com/GenieFramework/StippleDemos/blob/master/ReverseText.jl
https://github.com/GenieFramework/StippleDemos/blob/master/StippleButtons.jl

**Comment by szafna** [comment]
@essenciary there is a ```v-html``` directive in Quasar. 
Usage:
```<template>  <div v-html=\"solutionGridHTML\">  </div> </template>```

```solutionGridHTML``` is variable

Simon

**Comment by essenciary** [comment]
@szafna Thanks - not sure Quasar implements a `v-html`, it's rather part of Vue and is wrapped by `@html` in Stipple.
