### ISSUE TITLE
Menu example doesn't work

### ISSUE THREAD

**Issue by jonathanBieler** [GenieFramework/StippleUI.jl#93]
The example here doesn't work :

https://github.com/GenieFramework/StippleUI.jl/blob/6a44bc77060395a73687c13aa4859a29a303bb95/src/Menus.jl#L22

I think it should be something like :

```julia
btn("Basic Menu", color="primary", [
    StippleUI.menu(:menu, [p("Hello")])
])
```

**Comment by alerem18** [comment]
try this
```julia

function ui()
  Stipple.Html.div(id = "q-app", style = "min-height: 100vh;",
    Stipple.Html.div(class = "q-pa-md", [
            "",
        btndropdown(color = "primary", label = "Dropdown Button", [
                    "",
            item(clickable = "", vclosepopup = "", var"v-on:click" = "onItemClick", [
                            "",
                itemsection([
                                    "",
                    itemlabel(
                        "Photos"
                    ),
                    ""
                ]),
                ""
            ]),
            "",
            item(clickable = "", vclosepopup = "", var"v-on:click" = "onItemClick", [
                            "",
                itemsection([
                                    "",
                    itemlabel(
                        "Videos"
                    ),
                    ""
                ]),
                ""
            ]),
            "",
            item(clickable = "", vclosepopup = "", var"v-on:click" = "onItemClick", [
                            "",
                itemsection([
                                    "",
                    itemlabel(
                        "Articles"
                    ),
                    ""
                ]),
                ""
            ]),
            ""
        ]),
        ""
    ])
)
  
end
route("/") do 
  model = MyModel |> init
  page(model, ui()) |> html
end
```

**Comment by jonathanBieler** [comment]
Thank, but I'm not trying to get a menu working, just pointing out that the example in the docstring is broken.

**Comment by hhaensel** [comment]
Thanks @jonathanBieler for pointing this out. Your completely right here. Sorry for our late response.

@PGimenez , @essenciary 
We have conflicting names and conflicting syntax here between `Stipple.menu()` and  `StippleUI.menu()`.
We could import Stipple.menu in StippleUI, but we would need to force the supply of a fieldname, which is not so nice.
Alternatively we could define an additional `qmenu()` that doesn't conflict. Or we leave it as is but we don't export it but export an alias `const qmenu = StippleUI.menu`.

I would tend for the latter and released a respective PR #117.

**Comment by essenciary** [comment]
`Stipple.menu` comes from `Genie.Renderers.Html` as it's a HTML element. I would be tempted to no longer export `Genie.Renderers.Html.menu` which is probably safe (wonder if anybody uses `<menu>`?) but unfortunately breaking :(

**Comment by essenciary** [comment]
We could also patch it into `GenieFramework` to use `StippleUI.menu`

**Comment by hhaensel** [comment]
Well, that's difficult to decide. There are quite a lot of definitions in Html that collide with typical variable or function names. But there are also ones that might be used, e.g. `a()`, `p()`.
So should we remove only those that collide with quasar components?

**Comment by hhaensel** [comment]
all fixed with the latest PRs in Stipple and StippleUI.
`StippleUI.Menus.menu` is exported and `Genie.Renderers.Html.menu` is not.
